- name: variables from command line
  hosts: localhosts
  tasks:
  - name: print variable from command line
    ansible.builtin.debug:
    message: "the value of variable course is: {{COURSE}}"

# ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 -e COURSE=DevOps 07.vars-from-args.yaml  