- name: Declare variable at play level
  hosts: all
  vars:
    URL: play.example.com   #Play level we are assign variable we can call any task
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: Declare variable in another file
  hosts: all
  connection: local
  vars_files:
    - var.yaml
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
# vars_files can also be declared on task level.


- name: Declare variable at play level
  hosts: all
  connection: local #To run the script into local system
  tasks:
    - name: Declare and access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com     #We can access current task only

- name: Declare variable from inventory file
  hosts: all
  connection: local
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
# ansible-playbook -i inv vars.yaml


# ansible-playbook -i inv vars.yaml -e URL=cli.example.com -->Command Line Variables

- Variables are looking/executing for the below priority  (High to Low)
    - Command line Variables
    - Task Level
    - Variable from files
    - Play Level variables
    - Inventory variables



